apiVersion: v1
kind: Pod
metadata:
  name: runcontainererror-demo
spec:
  containers:
  - name: memory-hog
    image: busybox:1.36
    command: ["sh", "-c", "x=; while true; do x=$x$x$x$x; done"]
    resources:
      limits:
        memory: "2Mi"
        cpu: "100m"
      requests:
        memory: "2Mi"
        cpu: "50m"
