apiVersion: v1
kind: Pod
metadata:
  name: dns-failure-demo
spec:
  dnsPolicy: None
  dnsConfig:
    nameservers:
    - 1.2.3.4  # Invalid DNS server
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sh", "-c", "echo 'Searching for google dns'; nslookup www.google.co.uk || sleep 3600"]
