apiVersion: v1
kind: Pod
metadata:
  name: liveness-failure-demo
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    livenessProbe:
      httpGet:
        path: /nonexistent
        port: 80
      initialDelaySeconds: 2
      periodSeconds: 2
