apiVersion: v1
kind: Pod
metadata:
  name: unschedulable-affinity-demo
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nonexistent-label
            operator: In
            values:
            - does-not-exist
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sleep", "3600"]
