apiVersion: v1
kind: Pod
metadata:
  name: stuck-terminating-demo
  finalizers:
  - example.com/finalizer #Pod does not terminate cleanly. Pod does not terminate cleanly.
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    command: ["sh", "-c", "sleep 3600"]
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  terminationGracePeriodSeconds: 60
