apiVersion: v1
kind: Pod
metadata:
  name: pending-pod-demo
spec:
  containers:
  - name: sleep
    image: busybox:1.36
    command: ["sleep", "3600"]
    resources:
      requests:
        memory: "100Gi"
        cpu: "100"
