---
# VolumeMount or PVC Errors
# Cause: Volumes not attaching or mounting.
# Fix: Verify PVC status with kubectl get pvc, check storage class availability, and node-level permissions.
#
apiVersion: v1
kind: Pod
metadata:
  name: pvc-failure-demo
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: missing-pvc
  volumes:
  - name: missing-pvc
    persistentVolumeClaim:
      claimName: pvc-does-not-exist
