apiVersion: v1
kind: Pod
metadata:
  name: crashloop-demo
spec:
  containers:
  - name: crashing-container
    image: busybox:1.36
    command: ["sh", "-c", "echo 'Starting...'; sleep 2; exit 1"]
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
