apiVersion: v1
kind: Pod
metadata:
  name: stuck-containercreating-demo
spec:
  volumes:
  - name: nonexistent-pvc
    persistentVolumeClaim:
      claimName: pvc-does-not-exist
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: "/data"
      name: nonexistent-pvc
