---
# Pending Pods
# Cause: Pod cannot be scheduled to a node.
# Common Reasons: Lack of resources (CPU/mem), missing tolerations or node selectors, unsatisfiable affinities.
# Command: kubectl describe pod <pod> — look for "FailedScheduling".
# 
apiVersion: v1
kind: Pod
metadata:
  name: pending-pod-demo
spec:
  containers:
  - name: sleep
    image: busybox:1.36
    command: ["sleep", "3600"]
    resources:
      requests:
        memory: "100Gi"
        cpu: "100"
