---
# DNS Resolution Failures
# Cause: Pods can't resolve internal service names.
# Common Reasons: CoreDNS not working, wrong DNS policy, or network plugin issues.
# Fix: Check CoreDNS logs: kubectl logs -n kube-system -l k8s-app=kube-dns.
#
apiVersion: v1
kind: Pod
metadata:
  name: dns-failure-demo
spec:
  dnsPolicy: None
  dnsConfig:
    nameservers:
    - 1.2.3.4  # Invalid DNS server
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sh", "-c", "echo 'Searching for google dns'; nslookup www.google.co.uk || sleep 3600"]
