apiVersion: v1
kind: Pod
metadata:
  name: oomkilled-demo
spec:
  containers:
  - name: memory-hog
    image: python:3.9-slim
    command: ["python", "-c", "a = []; [a.append(' ' * 10**6) for _ in range(1000000) if True]"]
    resources:
      limits:
        memory: "32Mi"
        cpu: "100m"
      requests:
        memory: "32Mi"
        cpu: "50m"
